apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre  # Deployment name for managing PostgreSQL pods
spec:
  replicas: 1  # Creates one replica (one PostgreSQL pod)
  selector:
    matchLabels:  # Selector ensures pods have the label "app: postgre"
      app: postgre
  template:
    metadata:
      labels:  # Assigns the label "app: postgre" to pods created by this deployment
        app: postgre
    spec:
      containers:
      - name: postgre  # Container name within the pod
        image: postgres:13.1  # Docker image for the PostgreSQL database
        env:  # Environment variables for the container
          - name: POSTGRES_PASSWORD
            value: Pwd2024  # Password for the PostgreSQL user (consider using a secrets management tool)
          - name: POSTGRES_USER
            value: reviewfilmes  # Username for the PostgreSQL database
          - name: POSTGRES_DB
            value: reviewfilmes  # Name of the PostgreSQL database
        ports:  # Exposes the container port 5432 for service access
          - containerPort: 5432
---
apiVersion: v1
kind: service 
metadata: 
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    