name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo fonte
        uses: actions/checkout@v4.1.7
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção da imagem Docker e envio para o Docker hub
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            elieldiniz/review-filmes-test1:v${{github.run_number}}
            elieldiniz/review-filmes-test1:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do codigo fonte
        uses: actions/checkout@v4.1.7
      - name: Configuração do AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Configuração do Kubeconfig
        run: aws eks update-kubeconfig --name integracaopapeline
      - name: Deploy no kubernets
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            'elieldiniz/review-filmes-test1:v${{github.run_number }}'




  
  
    
