name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: passo 01
        run: echo "Construir a imagem da aplicação"
      - name: passo 02
        run: echo "Publicar a imagem no Docker hub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 01
        run: echo "Deploy da aplicação"
  
  
    
