name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo fonte
        uses: actions/checkout@v4.1.7
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: passo 01
        run: echo "Construir a imagem da aplicação"
      - name: passo 02
        run: echo "Publicar a imagem no Docker hub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 01
        run: echo "Deploy da aplicação"
  
  
    
